### ISSUE TITLE
Add seeder count

### ISSUE THREAD

**Issue by graphefruit** [QuantumBytesInc/ROAL#11]
@TobiasTrabelsi like discussed an actual seeder count (without IP etc.) would be cool.

**Comment by ManuelGysin** [comment]
What you mean exactly with count?

**Comment by Lerentis** [comment]
A representative number of people who seed the client if a user set the download type to torrent. 
With or without http Web seeds?

**Comment by ManuelGysin** [comment]
Just the number is enough?

**Comment by graphefruit** [comment]
Like: Online seeding users 13.
I thought just the torrent can be seeded, not the normal http?

**Comment by ManuelGysin** [comment]
Torrent supports HTTP seeders. We use cloudfront from Amazon as seeder.

**Comment by TobiasTrabelsi** [comment]
So I will include web seeding for now. If it is too misleading I will exclude it again.

**Comment by TobiasTrabelsi** [comment]
done and commited in testing #[b57c70e195be9c311fd2308668dd4e8698fbec6a]

**Comment by ManuelGysin** [comment]
Need merge to GUI.
