### ISSUE TITLE
Launcher adjustments for logging

### ISSUE THREAD

**Issue by ManuelGysin** [QuantumBytesInc/ROAL#12]
- Added constant file for errors and migrate errors to it
- Provide API access with documentation

**Comment by ManuelGysin** [comment]
@graphefruit 

Please add simple API with the to follwing end points:

- ../log-anonymous
- ../log

The first should be rate limited and can be used without authentication. The second one can only be called when authenticated with the token.

Log structure to accept:

`
{
   'log-level': 1,
   'log-message': 'test'
   'timestamp': 12.12.12 12:12:12
}
`
Model  to save:

- IP-Address IPField, not null
- Log-Level Integer, not null
- Log-Message Text, not null
- Timestamp Datetime, not null
- Account Link to Model, can be null for anonymous

**Comment by graphefruit** [comment]
@ManuelGysin Do we want to add a caller, action and code here aswell for error codes? Or do we want to support fire and forget (I don't think we realy would need it but we would be consistent then with all other interfaces)

**Comment by graphefruit** [comment]
@ManuelGysin Should this logged normal into database and not into google logging system? 
Do we need to log sensetive data or general loggings?
If general loggins why should we log ip-adress e.g.? We don't do it actualy in the other solutions aswell

**Comment by ManuelGysin** [comment]
logging must be fire and forget. we never log sensitive data. because with the ip we can reconstruct not authenticated sessions.

**Comment by graphefruit** [comment]
Will be implemented this week. Had now ROAP / ROAG on my first prior list.

**Comment by graphefruit** [comment]
Added.
Anonymous: 
- /interface/log_anonymous/

Datasample: {"LOG_LEVEL":1,"LOG_MESSAGE":"test","LOG_IP":"abcdef"}
- LOG_LEVEL: int / required
- LOG_MESSAGE: string / required
- LOG_IP: string / optional [if not set server will calculate ip]

Sample log: API - Log Anonymous: Level: 1, IP: 1.2.3.4, Model:-1, Message: test

Logged in:
-  /interface/log/
- Just can be called when logged in - Token needs to be added into header.

Datasample: {"LOG_LEVEL":1,"LOG_MESSAGE":"test","LOG_IP":"abcdef"}
- LOG_LEVEL: int / required
- LOG_MESSAGE: string / required
- LOG_IP: string / optional [if not set server will calculate ip]

Sample: API - Log: Level: 1, IP: 1.2.3.4, Model:2 (testing), Message: test
Model is added by server.

@ManuelGysin  @Lerentis - Please discuss who will implement this.

**Comment by graphefruit** [comment]
@Lerentis if you tested just give me or manuel a call. Please say timestamp so I can have a detailed look in logs then

**Comment by ManuelGysin** [comment]
Done.
