### ISSUE TITLE
Compilation Warnings and missing dependencies

### ISSUE THREAD

**Issue by ArchangeGabriel** [QuantumBytesInc/ROAL#7]
SFML and libarchive are needed compile and runtime dependencies (also boost seems to be only a compile time dependency). Maybe they should be added to README.

Also, they were some warnings issued during compilation:
```
src/cpp/httpdownload.cpp:331:66: attention : unused parameter ‘bytesTotal’ [-Wunused-parameter]
 void HttpDownload::downloadProgress(qint64 bytesReceived, qint64 bytesTotal)
                                                                  ^
src/cpp/httpdownload.cpp:339:52: attention : unused parameter ‘reply’ [-Wunused-parameter]
 void HttpDownload::slot_getSSLError(QNetworkReply* reply, const QList<QSslError> &errors)
                                                    ^
```
```
src/cpp/filedecompression.cpp: In member function ‘void FileDecompression::extract()’:
src/cpp/filedecompression.cpp:182:5: attention : ‘int archive_read_support_compression_all(archive*)’ is deprecated (declared at /usr/include/archive.h:311) [-Wdeprecated-declarations]
     archive_read_support_compression_all(a);
     ^
src/cpp/filedecompression.cpp:182:43: attention : ‘int archive_read_support_compression_all(archive*)’ is deprecated (declared at /usr/include/archive.h:311) [-Wdeprecated-declarations]
     archive_read_support_compression_all(a);
                                           ^
```
```
src/cpp/httpupdate.cpp:182:40: attention : unused parameter ‘_caller’ [-Wunused-parameter]
 void HttpUpdate::slot_checkVersion(int _caller, int _action, int _returnCode, QString _data)
                                        ^
src/cpp/httpupdate.cpp:182:53: attention : unused parameter ‘_action’ [-Wunused-parameter]
 void HttpUpdate::slot_checkVersion(int _caller, int _action, int _returnCode, QString _data)
                                                     ^
src/cpp/httpupdate.cpp:182:66: attention : unused parameter ‘_returnCode’ [-Wunused-parameter]
 void HttpUpdate::slot_checkVersion(int _caller, int _action, int _returnCode, QString _data)
                                                                  ^
```

**Comment by ManuelGysin** [comment]
Hello!

Thanks for the feedback!
I've added SFML as dependency. Boost is needed by libtorrent, so you have to have it installed. :)

The warnings will be fixed in the future but at the moment they cause no pain.

**Comment by ArchangeGabriel** [comment]
libtorrent-rasterbar depends on boost-libs, not boost itself, while boost is needed at compilation time. Anyway, most people have all these things pulled in because of other softs, so it does not matters a lot, it’s just a packaging thing.

Sure, warnings are warning, not errors, but I’m often very satisfied when I see a program compiling without warning. ;)

**Comment by ManuelGysin** [comment]
Year, but get some warnings out of the way can cause backward compatibility problems. One of them is "archive_read_support_compression_all", but I will try to use the new call "archive_read_support_filter_all". (The main problem is the windows version, the lib is somehow strange)

As of the other warnings, I'll have a look at them.

**Comment by ManuelGysin** [comment]
Fixed, QS pending then pushed to master.
